### PR TITLE
Handle null timeout messages

### LINKED ISSUE #1165: NPE in RemotingOkHttpCall.shouldRetry
## What happened?

Error bubbled up to root:
```
java.lang.NullPointerException:
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.shouldRetry(RemotingOkHttpCall.java:284)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall.access$300(RemotingOkHttpCall.java:60)
	at com.palantir.conjure.java.okhttp.RemotingOkHttpCall$3.onFailure(RemotingOkHttpCall.java:196)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:225)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.palantir.tracing.DeferredTracer.withTrace(DeferredTracer.java:115)
	at com.palantir.tracing.Tracers$TracingAwareCallable.call(Tracers.java:356)
	at com.palantir.tracing.WrappingExecutorService.lambda$wrapTask$0(WrappingExecutorService.java:67)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

Version: com.palantir.conjure.java.runtime:okhttp-clients:4.31.4
LOC: https://github.com/palantir/conjure-java-runtime/blob/4.31.4/okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java#L284

This must be `socketTimeout.getMessage()` returning `null`.

## What did you want to happen?

No NPE is thrown

### PR DESCRIPTION
**Pull request by raiju**
## Before this PR
Fix #1165 

## After this PR
==COMMIT_MSG==
Handle null socket timeout messages.
==COMMIT_MSG==

## Possible downsides?
This could mask bigger underlying issues.

### CODE REVIEW

File: okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java [hunk 1]
```diff
@@ -281,7 +281,8 @@ private boolean shouldRetry(IOException exception, Optional<Duration> backoff) {
                 if (exception instanceof SocketTimeoutException) {
                     // non-connect timeouts should not be retried
                     SocketTimeoutException socketTimeout = (SocketTimeoutException) exception;
-                    if (!socketTimeout.getMessage().contains("connect timed out")) {
+                    if (socketTimeout.getMessage() == null
+                            || !socketTimeout.getMessage().contains("connect timed out")) {
```
Comment (carterkozak) [inline okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java:285]: Any way we can reproduce this in a test?

Comment (raiju) [reply okhttp-clients/src/main/java/com/palantir/conjure/java/okhttp/RemotingOkHttpCall.java:285]: I don't have a real repro (not entirely sure how it happened, just have a trace to prove it did). I guess we could make a unit test, but don't think that'll help that much in making sure this type of regression happens again, or be particularly informative other than checking this particular method handles things correctly (e.g. I have no idea whether another bit of code will break somewhere else in this situation).

**Review by iamdanfox — APPROVED** [review]
OK let's give it a go
