### PR TITLE
Fix JaxRs RemoteException stack traces to include the call site

### LINKED ISSUE #670: Hard to read stack traces when synchronous Jaxrs calls receives a RemoteException
## Repro:

1. Set up an endpoint which always throws RemoteExceptions
1. Make a call to this endpoint using a `JaxRsClient`
1. Look at the stack trace

## Actual:

The stack trace does not contain enough information to locate the call site, e.g.:
```
com.palantir.remoting.api.errors.RemoteException: RemoteException: INTERNAL (Default:Internal) with instance ID cfc0ee0b-e51f-447d-85c2-5f5103e00204

	at com.palantir.remoting3.okhttp.RemoteExceptionResponseHandler.handle(RemoteExceptionResponseHandler.java:62)
	at com.palantir.remoting3.okhttp.RemotingOkHttpCall$2.onResponse(RemotingOkHttpCall.java:191)
	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable$$Lambda$55/1567259120.call(Unknown Source)
	at com.palantir.remoting3.tracing.DeferredTracer.withTrace(DeferredTracer.java:43)
	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:182)
	at com.palantir.remoting3.tracing.WrappingExecutorService.lambda$wrapTask$6(WrappingExecutorService.java:70)
	at com.palantir.remoting3.tracing.WrappingExecutorService$$Lambda$54/690052870.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

## Expected:

The stacktrace you see when a call fails should include enough information that you can figure out where in user-authored code the call came from.  Note, this is the case for IOExceptions.

cc @ellisjoe

### PR DESCRIPTION
**Pull request by iamdanfox**
fixes https://github.com/palantir/http-remoting/issues/670

On the RemoteException codepath, we now never throw _any_ information away, so you get nice clear stack traces like this:

```diff
 com.palantir.remoting.api.errors.RemoteException: RemoteException: INTERNAL (Default:Internal) with instance ID 605b5f20-a83a-46c9-a207-cf60764b7975
 	at com.palantir.remoting3.okhttp.RemotingOkHttpCall.execute(RemotingOkHttpCall.java:117)
 	at feign.okhttp.OkHttpClient.execute(OkHttpClient.java:155)
 	at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:97)
 	at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:76)
 	at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)
 	at com.sun.proxy.$Proxy14.string(Unknown Source)
+	at com.palantir.remoting3.jaxrs.JaxRsClientStackTraceTest.stack_trace_from_remote_exception_should_include_call_site(JaxRsClientStackTraceTest.java:68)
 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
 	at java.lang.reflect.Method.invoke(Method.java:497)
 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
 	...
 Caused by: java.util.concurrent.ExecutionException: com.palantir.remoting3.okhttp.IoRemoteException
 	at com.google.common.util.concurrent.AbstractFuture.getDoneValue(AbstractFuture.java:500)
 	at com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:401)
 	at com.google.common.util.concurrent.AbstractFuture$TrustedFuture.get(AbstractFuture.java:83)
 	at com.palantir.remoting3.okhttp.RemotingOkHttpCall.execute(RemotingOkHttpCall.java:106)
 	... 39 more
 Caused by: com.palantir.remoting3.okhttp.IoRemoteException
 	at com.palantir.remoting3.okhttp.RemotingOkHttpCall$2.onResponse(RemotingOkHttpCall.java:198)
 	at okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
 	at okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
 	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable$$Lambda$55/695883542.call(Unknown Source)
 	at com.palantir.remoting3.tracing.DeferredTracer.withTrace(DeferredTracer.java:43)
 	at com.palantir.remoting3.tracing.Tracers$TracingAwareCallable.call(Tracers.java:182)
 	at com.palantir.remoting3.tracing.WrappingExecutorService.lambda$wrapTask$6(WrappingExecutorService.java:70)
 	at com.palantir.remoting3.tracing.WrappingExecutorService$$Lambda$54/1276709283.run(Unknown Source)
 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
 	at java.lang.Thread.run(Thread.java:745)
```

### CODE REVIEW

File: jaxrs-clients/src/test/java/com/palantir/remoting3/jaxrs/JaxRsClientStackTraceTest.java [hunk 1]
```diff
@@ -0,0 +1,84 @@
...
+    @Test
+    public void stack_trace_from_ioexception_should_include_call_site() throws Exception {
+        server1.shutdown();
+
+        try {
+            proxy.string();
+            failBecauseExceptionWasNotThrown(Exception.class);
+        } catch (Exception e) {
+            assertThat(e).hasStackTraceContaining("JaxRsClientStackTraceTest."
+                    + "stack_trace_from_ioexception_should_include_call_site(JaxRsClientStackTraceTest.java:");
```
Comment (ellisjoe) [inline jaxrs-clients/src/test/java/com/palantir/remoting3/jaxrs/JaxRsClientStackTraceTest.java:59]: also assert that it contains `proxy.string()`

**Comment by ellisjoe** [comment]
sweet

File: jaxrs-clients/src/test/java/com/palantir/remoting3/jaxrs/JaxRsClientStackTraceTest.java (hunk 1 above)
Comment (ellisjoe) [reply jaxrs-clients/src/test/java/com/palantir/remoting3/jaxrs/JaxRsClientStackTraceTest.java:59]: oh don't think that'll work since it's a proxy

**Review by ellisjoe — APPROVED** [review]
