### PR TITLE
Decode general web exceptions

### LINKED ISSUE #24: SerializableErrorErrorDecoder.java fails on exceptions without a single-string constructor
BLUF: Failure to parse error body for any HTTP statuses other than a few of the most common

In https://github.com/palantir/http-remoting/blob/develop/http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java, "exceptionClass.getConstructor(String.class)" requires that the exception has a constructor that takes a single String. This is reasonable for the HTTP statuses that have a a specific exception made for them (e.g. BadRequestException, ForbiddenException), but for all the other statuses, you have to use either a ClientErrorException or ServerErrorException, which do not have single-string constructors.

Hacky workarounds are possible: I wrote code in Contour the catches HTTP-remoting exception and searches the message for the right HTTP status code. :/

### PR DESCRIPTION
**Pull request by TheBeruriahIncident**
Previously, exceptions corresponding to specific HTTP error codes (e.g. BadRequestException) would be properly decoded, but more general exceptions that just hold a status value (e.g. ClientErrorException) would fail to decode.

We now handle:
- WebApplicationException
- ServerErrorException
- ClientErrorException

Fixes #24

### CODE REVIEW

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 1]
```diff
@@ -115,6 +118,25 @@ private static Exception constructException(
...
+                // the message should be of the form "HTTP $STATUS $DESCRIPTION
+                // for example, "HTTP 501 Not Implemented"
+                int prefixLength = "HTTP ".length();
+                String statusAsString = message.substring(prefixLength, prefixLength + 3);
+                int status = Integer.parseInt(statusAsString);
+
+                // WebApplicationException has a different order in its constructor arguments
+                if (exceptionClass.equals(WebApplicationException.class)) {
+                    return exceptionClass.getConstructor(Throwable.class, Integer.TYPE)
+                            .newInstance(wrappedException, status);
```
Comment (markelliot) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: how about:

```
return new WebApplicationException(wrappedException, status);
```

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 2]
```diff
@@ -115,6 +118,25 @@ private static Exception constructException(
         // Note: If another constructor is added, then we should refactor the construction logic in order to avoid
         // nested try/catch
         try {
+            if (exceptionClass.equals(ClientErrorException.class)
```
Comment (markelliot) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: this would also need to appear in the other `constructException` block for it to generally work, which makes me think the test coverage you're committing isn't sufficient.

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 3]
```diff
@@ -115,6 +118,25 @@ private static Exception constructException(
...
+                    || exceptionClass.equals(ServerErrorException.class)
+                    || exceptionClass.equals(WebApplicationException.class)) {
+                // the message should be of the form "HTTP $STATUS $DESCRIPTION
+                // for example, "HTTP 501 Not Implemented"
+                int prefixLength = "HTTP ".length();
+                String statusAsString = message.substring(prefixLength, prefixLength + 3);
+                int status = Integer.parseInt(statusAsString);
```
Comment (markelliot) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: I think maybe we should just put the regex in here, don't care about perf in the exception handler and would prefer something more readable

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java (hunk 2 above)
Comment (markelliot) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: or do these actually have a single-string arg constructor?

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 4]
```diff
@@ -115,6 +118,25 @@ private static Exception constructException(
         // Note: If another constructor is added, then we should refactor the construction logic in order to avoid
```
Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java:121]: I believe that this comment applies to this change. Introducing more special cases turns this into spaghetti.

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 5]
```diff
@@ -115,6 +118,25 @@ private static Exception constructException(
...
         // nested try/catch
         try {
+            if (exceptionClass.equals(ClientErrorException.class)
+                    || exceptionClass.equals(ServerErrorException.class)
+                    || exceptionClass.equals(WebApplicationException.class)) {
+                // the message should be of the form "HTTP $STATUS $DESCRIPTION
+                // for example, "HTTP 501 Not Implemented"
+                int prefixLength = "HTTP ".length();
+                String statusAsString = message.substring(prefixLength, prefixLength + 3);
```
Comment (schlosna) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: This may `throw IndexOutOfBoundsException` if the message doesn't contain "HTTP " or is length less than 5. Could also NPE if message is null.

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java (hunk 3 above)
Comment (schlosna) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: Would also avoid possible problems where statusAsString is non-numeric and won't parse.

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 6]
```diff
@@ -115,6 +118,25 @@ private static Exception constructException(
         // Note: If another constructor is added, then we should refactor the construction logic in order to avoid
         // nested try/catch
         try {
+            if (exceptionClass.equals(ClientErrorException.class)
+                    || exceptionClass.equals(ServerErrorException.class)
+                    || exceptionClass.equals(WebApplicationException.class)) {
```
Comment (schlosna) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: Why not do `WebApplicationException.class.isAssignableFrom(exceptionClass)` to cover all of these cases or do you want to explicitly exclude `javax.ws.rs.RedirectionException`?

Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: We want to exclude all of the Exception classes that were already handled. `BadRequestException`, `NotFoundException`, etc all have single-string constructors, but are children of WebApplicationException.

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java (hunk 2 above)
Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: Ah, the other `constructException` was returning `RuntimeException`, will fix!

**Comment by TheBeruriahIncident** [comment]
@markelliot , I made an oversight in that you can construct these exceptions in such a way that the message itself won't have the status, meaning that the status only lives as a field in the `Response`. As such, the `SerializableException` doesn't necessarily have enough info to actually reconstruct the exception. Is it reasonable to add a `status` field to `SerializableException`?

**Comment by TheBeruriahIncident** [comment]
@markelliot Are you good with adding `status` to `SerializableException`?

**Comment by uschi2000** [comment]
@akroy why do you need it in the exception if it's already in the response?

**Comment by TheBeruriahIncident** [comment]
@uschi2000 We don't currently put the status in the response. We've special cased a few exception types, but most everything just gets a generic 500 as the response status.

(I was planning on following this up with making an exception mapper that actually uses statuses) My (guessed) interpretation was that we were intentionally only using the `SerializableException` info for serialization, but if encoding the status in the response is fine, I'll work on our exception mappers first.

**Comment by markelliot** [comment]
The response code is available from the literal http response, Adam, we shouldn't be additionally serializing it into the data structure.

**Comment by TheBeruriahIncident** [comment]
Great. I'll close this out and add exception mapping that puts the status into the http response, and I'll reopen after that's fixed.

**Comment by markelliot** [comment]
the status is already placed into the HTTP response.

**Comment by TheBeruriahIncident** [comment]
Specific statuses are placed there for `FORBIDDEN` and `NOT_FOUND`, and we have handling for `IllegalArgumentException`, but from what I can tell/observe, most exceptions are handled by the `RuntimeExceptionMapper`, which just uses 500 no matter what.

**Comment by markelliot** [comment]
- @pnepywoda

This doesn't quite jive with my recollection. I'm pretty sure if you return a WebAppException we pull out the error code.

**Comment by TheBeruriahIncident** [comment]
I don't see any relevant mapper in: https://github.com/palantir/http-remoting/tree/develop/http-servers/src/main/java/com/palantir/remoting/http/server . I did write the (fairly small) PR to fix that though, I'll put it up in a sec

**Comment by markelliot** [comment]
Ok, happy to look at the pr.

**Comment by TheBeruriahIncident** [comment]
PR at https://github.com/palantir/http-remoting/pull/48

**Comment by TheBeruriahIncident** [comment]
@markelliot @uschi2000 @schlosna Redid this now that we can assume the status is right

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 7]
```diff
@@ -112,7 +125,15 @@ private static Exception constructException(Class<? extends Exception> exception
...
     private static Exception constructException(
-            Class<? extends Exception> exceptionClass, String message, Throwable wrappedException) {
+            Class<? extends Exception> exceptionClass, String message, Throwable wrappedException, int status) {
+        if (exceptionClass.equals(ClientErrorException.class)) {
+            return new ClientErrorException(status, wrappedException);
+        } else if (exceptionClass.equals(ServerErrorException.class)) {
+            return new ServerErrorException(status, wrappedException);
+        } else if (exceptionClass.equals(WebApplicationException.class)) {
+            return new WebApplicationException(wrappedException, status);
+        }
```
Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java:119]: I'm not enthused about having this similar block twice, but since in one case we wrap the exception, more DRY approaches seem much less clean.

Similarly, I'm not a fan of having two different `if`s for Client and Server, but that lets us remove the reflection and take this out of the try-catch block.

Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java:119]: you can `initCause()`; it's "clean enough" since it enforces (at runtime) that it's called at most once.

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 8]
```diff
@@ -101,7 +106,15 @@ public Exception decode(String methodKey, Response response) {
         }
     }
 
-    private static Exception constructException(Class<? extends Exception> exceptionClass, String message) {
+    private static Exception constructException(Class<? extends Exception> exceptionClass, String message, int status) {
+        if (exceptionClass.equals(ClientErrorException.class)) {
```
Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java:113]: what about the message?

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java (hunk 7 above)
Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java:119]: Just tried that: apparently all the WebApplicationExceptions call into a single constructor that takes cause, meaning that they're all setting cause to `null` if you don't set it. This prevents us from setting it with `initCause`, because of the "set once" limitation.

**Comment by TheBeruriahIncident** [comment]
@uschi2000 Using message, improved tests

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java (hunk 4 above)
Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java:121]: Any opinion here?

Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java:121]: That comment seems to be about the nested try-catch and a worry about nesting further. My change doesn't touch any of that, so I don't think it makes that situation worse. It may be possible to clean that block up, but I think that's a separate issue.

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 9]
```diff
@@ -101,7 +106,15 @@ public Exception decode(String methodKey, Response response) {
         }
     }
 
-    private static Exception constructException(Class<? extends Exception> exceptionClass, String message) {
+    private static Exception constructException(Class<? extends Exception> exceptionClass, String message, int status) {
```
Comment (markelliot) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: looking at http://grepcode.com/file/repo1.maven.org/maven2/javax.ws.rs/javax.ws.rs-api/2.0.1/javax/ws/rs/WebApplicationException.java#65 I think this method ought to simply invoke:

```
return constructException(exceptionClass, message, null, status);
```

...and that that would be a lot less duplicate code.

Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: Collapsed the two methods into one

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 10]
```diff
@@ -101,18 +106,16 @@ public Exception decode(String methodKey, Response response) {
...
     }
 
-    private static Exception constructException(Class<? extends Exception> exceptionClass, String message) {
-        try {
-            return exceptionClass.getConstructor(String.class).newInstance(message);
-        } catch (Exception e1) {
-            return new RuntimeException(String.format(
-                    "Failed to construction exception of type %s, constructing RuntimeException instead: %s%n%s",
-                    exceptionClass.toString(), e1.toString(), message));
+    private static Exception constructException(
```
Comment (jlzhao27) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: I don't think this change is correct. The problem I noticed is that the server side `JsonExceptionMapper` is capturing the web specific exceptions like 405 Not Allowed and throwing them as a 500. I think the fix needs to be in the exception mapper to throw the right status code (and we should also decode the exception).

Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: Hey Jason! HTTP-remoting's handling of exceptions was actually doubly broken:
- most exceptions were thrown as 500s on server side (what you're mentioning)
- most exceptions were failing to decode on client side (what this commit is)

Both of these errors were related to the same failure to deal with WebApplication, ClientError, or ServerError exceptions, just in different places. I already fixed the problem you mention at https://github.com/palantir/http-remoting/pull/48 .

Comment (jlzhao27) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: oh doh, thanks adam! neither of these changes are released yet right?

Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: nope. we can release 0.7.0 today. it's a major breaking change, both in
terms of code and config.

Comment (TheBeruriahIncident) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: Not yet! Server side fix is merged (so you could snapshot). On https://github.com/palantir/http-remoting/pull/35, @uschi2000 said that we'll likely release 0.7.0 once my fixes go in.

**Comment by TheBeruriahIncident** [comment]
@markelliot @uschi2000 How does this look?

**Comment by jlzhao27** [comment]
ping on this also, GK is waiting on the 0.7.0 release :)

**Comment by markelliot** [comment]
seems okay to me

**Comment by TheBeruriahIncident** [comment]
Sweet. I'm going to squash and rebase

**Comment by TheBeruriahIncident** [comment]
@markelliot Ready!

File: http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java [hunk 11]
```diff
@@ -101,18 +106,16 @@ public Exception decode(String methodKey, Response response) {
...
+            Class<? extends Exception> exceptionClass, String message, int status, Throwable wrappedException) {
```
Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: @CheckForNull missing

Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: or probably `Optional<Throwable>`

Comment (uschi2000) [inline http-clients/src/main/java/com/palantir/remoting/http/errors/SerializableErrorErrorDecoder.java]: and please leave a comment saying that sub-class of RuntimeException can take a `null` cause parameter to indicate an unknown cause.

**Comment by uschi2000** [comment]
one last comment above, hopefully.
