### PR TITLE
compare fqdn case insensitively and paths case sensitively

### LINKED ISSUE #377: Does http-remoting automatically lower case uris?
I'm generating a Retrofit2Client with a URI whose FQDN has upper case letters. When I actually make a request with that client, I hit this error: https://github.com/palantir/http-remoting/blob/ae3be5349b1634183798ff52cc5df40925af7840/retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java#L101

"Unrecognized server URI in the request `lower case fqdn`. Supported servers are `original upper case fqdn`". 

Should we be doing case insensitive comparisons instead?

cc @uschi2000

### PR DESCRIPTION
**Pull request by rahij**
Fixes #377 

cc @ash211 @uschi2000

---
This change is [Reviewable](https://reviewable.io/reviews/palantir/http-remoting/378)

### CODE REVIEW

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java [hunk 1]
```diff
@@ -86,12 +86,12 @@ public Response intercept(Chain chain) throws IOException {
...
 
     private Request redirectRequest(Request request, String redirectToUri) {
-        String requestUri = request.url().toString();
+        HttpUrl requestUrl = request.url();
 
         String matchingUri = null;
         // Find which server from `uris` is used in the current request, then ...
         for (String uri : uris) {
-            if (requestUri.startsWith(uri)) {
+            if (doServersMatch(requestUrl, HttpUrl.parse(uri))) {
```
Comment (uschi2000) [inline retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: want to keep a List<HttpUrl> instead of strings?

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java [hunk 2]
```diff
@@ -86,12 +86,12 @@ public Response intercept(Chain chain) throws IOException {
     }
 
     private Request redirectRequest(Request request, String redirectToUri) {
-        String requestUri = request.url().toString();
+        HttpUrl requestUrl = request.url();
 
         String matchingUri = null;
         // Find which server from `uris` is used in the current request, then ...
         for (String uri : uris) {
```
Comment (uschi2000) [inline retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: pick one or the other: uri/url

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java [hunk 3]
```diff
@@ -100,16 +100,26 @@ private Request redirectRequest(Request request, String redirectToUri) {
...
+        String newRequestUrl = requestUrl.toString().replaceFirst(matchingUri, redirectToUri);
         return request.newBuilder()
                 .url(HttpUrl.parse(newRequestUrl))
                 // Request.this.tag field by default points to request itself if it was not set in RequestBuilder.
                 // We don't want to reference old request in new one - that is why we need to reset tag to null.
                 .tag(request.tag().equals(request) ? null : request.tag())
                 .build();
     }
+
+    private boolean doServersMatch(HttpUrl serverUri, HttpUrl server) {
```
Comment (uschi2000) [inline retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: - docs, please
- parameters should have symmetric names; for instance `left`, `right`
// edit: scrap that, it's not symmetric. so how about: fullUrl vs prefixUrl or something like that.

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java [hunk 4]
```diff
@@ -100,16 +100,26 @@ private Request redirectRequest(Request request, String redirectToUri) {
...
+        String serverUriFqdn = String.format("%s://%s:%s", serverUri.scheme(), serverUri.host(), serverUri.port());
```
Comment (uschi2000) [inline retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: as above... `leftFqdn` and `rightFqdn`

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java [hunk 5]
```diff
@@ -100,16 +100,26 @@ private Request redirectRequest(Request request, String redirectToUri) {
...
+        String serverUriPath = serverUri.encodedPath();
+
+        String serverFqdn = String.format("%s://%s:%s", server.scheme(), server.host(), server.port());
```
Comment (uschi2000) [inline retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: actually, let's do something like this:
```
// does HttpUrl::host always return a lowercase host?
private static final Comparator<HttpUrl> FQDN_COMPARATOR = Comparator.comparing(HttpUri::scheme).thenComparing(HttpUri::host).thenComparing(HttpUri::port);

boolean startsWith(HttpUrl fullUrl, HttpUrl prefixUrl) {
  return
    FQDN_COMPARATOR.compare(fullUrl, prefixUrl) == 0
    && fullUrl.encodedPath().startsWith(prefixUrl.encodedPath());
}
```

File: retrofit2-clients/src/test/java/com/palantir/remoting2/retrofit2/TestService.java [hunk 6]
```diff
@@ -51,4 +51,7 @@
     // Note: Retrofit2 will discard any baseUrl path when the endpoint path starts with "/"
     @GET("/absolute")
     Call<String> getAbsolute();
+
+    @GET("/Api")
+    Call<String> getAbsoluteApiTitleCase();
```
Comment (uschi2000) [inline retrofit2-clients/src/test/java/com/palantir/remoting2/retrofit2/TestService.java:56]: can just use one of the existing endpoints for the new tests

Comment (rahij) [reply retrofit2-clients/src/test/java/com/palantir/remoting2/retrofit2/TestService.java:56]: I need an absolute url with uppercase letters in it in order to test this correctly :/

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java (hunk 2 above)
Comment (rahij) [reply retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: We seem to use uri everywhere including when calling the constructors and the Request object has `url` anyway. I could pass a String to doServersMatch for the prefixUrl, but not sure if that's any cleaner

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java (hunk 5 above)
Comment (rahij) [reply retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: Done. Yes, it does return a lower case host.

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java (hunk 1 above)
Comment (uschi2000) [reply retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: ah, swallowed some characters, sorry; wondering if the class should keep a `List<HttpUrl>` instead of a `List<String>`?

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java (hunk 2 above)
Comment (uschi2000) [reply retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: ok

File: retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java (hunk 1 above)
Comment (rahij) [reply retrofit2-clients/src/main/java/com/palantir/remoting2/retrofit2/MultiServerRetryInterceptor.java]: Yeah good idea. Done

**Review by uschi2000 — APPROVED** [review]
